on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Validate JSON sytax
    steps:
      - uses: actions/checkout@v3
      - id: myValidator
        uses: snaksa/json-syntax-validator
        with:
          paths: './data/success.json,./data/error.json'